### PR TITLE
Add CMake support

### PR DESCRIPTION
**Pull request by FMeinicke**
Hi, I'm currently working on a larger project that needs cross-platform zeroconf support. However, I'm using CMake as build system so I thought it would nice to be able to integrate QtZeroConf via CMake.
I found that [cor3ntin](https://github.com/cor3ntin) already did some modifications and added a basic CMakeLists.txt (unfortunately, he deleted his fork of the repo). This was a really good starting point for me. I built on top of that and just modernized the CMakeLists a bit and fixed some stuff that didn't work properly.

What this PR introduces is:
- a `QtZeroConf` CMake project that builds either a shared or a static library (configurable through the standard `BUILD_SHARED_LIBS` variable) on Windows (tested), Linux (tested), MacOS (not tested) and Android (not tested)
- an installable CMake target for QtZeroConf
- another CMake project for the example application that uses the QtZeroConf target from the main CMake project

### CODE REVIEW

**Comment by jbagg** [comment]
HI Thank you for this new feature!  There is an unrelated change included in qzeroconfservice.h.  Is there a way I can just merge the other three files in your pull request?  Jon

**Comment by FMeinicke** [comment]
Oops. Just saw that. That must have been my auto-format. I'm gonna update the PR later and remove that unrelated change.

**Comment by FMeinicke** [comment]
Hi, so I removed that change now. However, it wasn't my auto-format as I suspected yesterday (I was using GitHub's mobile app so I didn't read the code correctly). Instead, I had to add the `Q_ZEROCONF_EXPORT` macro to the `operator<<` in qzeroconfservice.h. Otherwise, I would be getting a linker error on Windows because the debug operator wouldn't be properly exported in a DLL.

I can see how this might seem unrelated to this particular PR for you. However, I'd still like to see add change. I can make a separate PR if you prefer that.

**Comment by jbagg** [comment]
ok, Please do a separate PR to add the Q_ZEROCONF_EXPORT to operator<<

**Pull request merged**
