### PR TITLE
Fix clang compiler errors and warnings

### PR DESCRIPTION
**Pull request by mincequi**
Fixed some warnings and errors when compiling with clang on OSX.

Btw. which IDE do you use? QtCreator? Which code style do you apply? I could not find something appropriate.
What do you think about QtCreators default style? (using spaces instead of tabs, use one-true-brace-style).

### CODE REVIEW

**Review by jbagg — CHANGES_REQUESTED** [review]
Hi, Please do not commit white space changes along with functional changes.  This makes it look like the clang warnings are from the white space.

Changes from NULL to nullptr are welcome.

Some of your changes utilize the c++11 member initialization feature.  I think (?) QtZeroConf will still compile on pre c++11 toolchains so I would need to investigate if c++11 features will break current compatibility.

I use the QtCreator default formatting with one change; the "tab policy" is set to "tabs only" (Tabs for indentation; spaces for alignment)

**Comment by mincequi** [comment]
Ok, I will just do functional changes.

You also do the member initialization in the Resolver class within bonjour_p.h. So, we should be fine.

I will do an update on this PR.

**Comment by jbagg** [comment]
Would you mind sending me a patch of this change instead of using github's pull request?  I rebased master and I'm not sure what the github tools will do to the history.  Git will still show you as the committer when I sign off.  

git format-patch -n HEAD^

**Comment by mincequi** [comment]
[0001-Fix-clang-compiler-errors-and-warnings.patch.zip](https://github.com/jbagg/QtZeroConf/files/4402361/0001-Fix-clang-compiler-errors-and-warnings.patch.zip)

Github behaves the same here as regular git: when you rebase, my changes get applied on top (making them the most recent commit).

See attached patch.

**Comment by jbagg** [comment]
Manually signed off on this change in commit [5c4b](https://github.com/jbagg/QtZeroConf/commit/5c4bdf1a567dcc9d29ef3957b07f05aaa538b68f)

**Pull request closed without merging**
