### PR TITLE
fix for gcc compilation on windows

### PR DESCRIPTION
**Pull request by rumengb**

### CODE REVIEW

**Comment by FMeinicke** [comment]
Hey @jbagg, I've also had the issue that this PR addresses. Would you be willing to merge this into master?

**Comment by jbagg** [comment]
I don't like fixing this in QtZeroConf as this file comes from Apple's SDK.  When I bring in newer SDKs, I'm sure I'll forgot about this modification.

**Comment by FMeinicke** [comment]
Oh, ok. Well, is there anyway we could bring this fix into Apple's SDK directly? So that the next time you update the SDK this issue has already been resolved.

But thank you for merging, still :)

**Comment by rumengb** [comment]
Do not worry :) I will make another PR when my build fails :)

**Pull request merged**
